### ISSUE TITLE
Can Gamma be a variable?

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#14]
(For goal programming) I added SimPleAC_goal to robustSPpaper/code, and when I made Gamma a variable there I got the following error:
```python
run SimPleAC_goal
SP is not converging! Last GP iteration had a higher cost (5.8e+02) than the previous one (5.1e+02). Results for each iteration are in (Model).program.results. If your model contains SignomialEqualities, note that convergence is not guaranteed: try replacing any SigEqs you can and solving again.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\code\robustSPpaper\code\SimPleAC_goal.py in <module>()
     15     Gamma = Variable('\Gamma','-','Uncertainty bound')
     16     m = Model(1/Gamma, [m, m.cost <= sol['cost']*1.2, Gamma <= 1e30])
---> 17     rm = RobustModel(m, 'elliptical', twoTerm=False, gamma=Gamma)
     18     rmsol = rm.robustsolve(verbosity=0)  # solve the robust model
     19

c:\users\berk\dropbox (mit)\mit graduate school\code\robust\robust\robust.pyc in __init__(self, model, type_of_uncertainty_set, **options)
    143         self.number_of_gp_posynomials = len(gp_posynomials)
    144
--> 145         constraints_posynomials_tuple = self.classify_gp_constraints(gp_posynomials)
    146
    147         self.ready_gp_constraints += constraints_posynomials_tuple[0]

c:\users\berk\dropbox (mit)\mit graduate school\code\robust\robust\robust.pyc in classify_gp_constraints(self, gp_posynomials, offset)
    262         for i, p in enumerate(data_gp_posynomials):
    263             if len(p.exps) == 1:
--> 264                 robust_monomial = self.robustify_monomial(p)
    265                 ready_gp_constraints += [robust_monomial <= 1]
    266             elif len(p.exps) == 2 and self.setting.get('linearizeTwoTerm'):

c:\users\berk\dropbox (mit)\mit graduate school\code\robust\robust\robust.pyc in robustify_monomial(self, monomial)
    287         for var in m_direct_uncertain_vars:
    288             eta_min, eta_max = RobustGPTools.generate_etas(var, self.type_of_uncertainty_set,
--> 289                                                            self.number_of_stds, self.setting)
    290             center = (eta_min + eta_max) / 2.0
    291             scale = eta_max - center

c:\users\berk\dropbox (mit)\mit graduate school\code\robust\robust\robust_gp_tools.pyc in generate_etas(var, type_of_uncertainty_set, number_of_stds, setting)
     52                 elif type_of_uncertainty_set == 'elliptical':
     53                     pr = var.key.pr * setting.get("gamma")
---> 54                     eta_max = np.log(1 + pr / 100.0)
     55                     eta_min = np.log(1 - pr / 100.0)
     56         return eta_min, eta_max

AttributeError: 'Posynomial' object has no attribute 'log'
```
I guess here you are trying to take a log of the Gamma variable, so I am wondering if you can even make it a variable in the current code? @alisaab

**Comment by 1ozturkbe** [comment]
@alisaab any updates on this?

**Comment by alisaab** [comment]
@1ozturkbe , check the robustSPpaper branch, the pr in each variable should be replaced by r, where the upper and lower limit for each variable is nominal_value*r and the lowest value is nominal_value/r. I did this change for the simple_problem. Also, gamma >= 1 now, and the default value of gamma is np.exp(1). 

I suggest doing the following to replace the "pr"s by "r"s:

the new nominal value = old_value*np.sqrt(1 - pr**2/1e4), and r = np.sqrt((100+pr)/(100-pr)).

you can use this function:

def calc(val, pr):
    return val*np.sqrt(1-pr**2/1e4), np.sqrt((100+pr)/(100-pr))

**Comment by 1ozturkbe** [comment]
I think this is a bit janky. The model should be able to handle goal programming for both pr and r inputs. I will try to modify robust so that this is the case.

**Comment by 1ozturkbe** [comment]
Also, I can't even get the current code to run. Are you sure you are able to run SimPleAC_goal? Because I am still getting errors 'taking the log of Posynomial'.

**Comment by alisaab** [comment]
Yes sure, I tried it, you have to be on the robustSPpaper branch on robust.

**Comment by 1ozturkbe** [comment]
oh crud, didn't realize we needed different branches of literally everything. Will do!

**Comment by 1ozturkbe** [comment]
Works, cool!

**Comment by 1ozturkbe** [comment]
(wow, robust looks a lot cleaner with that last update!) Alright, this creates a few conundrums I think that need to be addressed. 
-> What if the user puts in both a pr and r but they don't match? 
I think we should assert that they are within a certain tolerance, and ask the user to change it if they are not. 
-> Also, it's confusing that r and pr are centered around different means. 
These could both be fixed by making r the default uncertainty bound. What do you think?

**Comment by 1ozturkbe** [comment]
Also, this is super exciting that it worked! I can't wait to play around with it and write it up.

**Comment by alisaab** [comment]
On the master branch, a user can specify both pr and r for each variable. The pr will be used for box uncertainty set, if pr is not specified then r will be used. For elliptical it is the opposite, r will be used and if not specified then pr will be used.

if pr is specified, then the value is the center of the interval  in real space (exponential space), while if r is specified, then the value is the center of the interval in log-space.

**Comment by alisaab** [comment]
> I think this is a bit janky. The model should be able to handle goal programming for both pr and r inputs. I will try to modify robust so that this is the case.

The thing is that when using pr, we should either take the log Gamma, or accept the fact that for Gamma=0, the nominal problem will not be solved, but another problem with shifted substitutions.

**Comment by 1ozturkbe** [comment]
As of most recent master, both pr and r are valid inputs. Furthermore, Gamma can be a variable, so we can close this.
