### ISSUE TITLE
Why choose to sample from uniform for probability of failure? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#19]
Hello @alisaab, I just noticed that when you generate the directly_uncertain_vars_subs that you pull them from a uniform distribution within the box uncertainty set. Wouldn't it make more sense to pull them from some kind of Gaussian, as to 'restrict nature' per Bertsimas? Pulling from the uniform, although  may result in some pretty pessimistic probability of failure analyses, especially for a signomial model where the uncertain variable interactions are more complex. I think a better alternative may be pulling from a Gaussian, or even truncated Gaussian if you think bounded support is a requirement. What do you think?

**Comment by alisaab** [comment]
I used to simulate for both Uniform and Gaussian, I chose to go for uniform distribution to be consistent with the idea of an uncertainty set where all realizations are equal in importance. I would say that sampling from a Uniform distribution is better for testing the solution from an abstract point of view as it is more consistent with the notion of an uncertainty set, however, sampling from a Gaussian distribution makes more sense if we are testing a design as you mentioned.

**Comment by whoburg** [comment]
Is exposing both options to the user straightforward? Would that fundamentally change something downstream or make the math more complicated?

**Comment by alisaab** [comment]
Yes it can be kept as a choice for the user, we should probably do this

**Comment by 1ozturkbe** [comment]
I understand your choice to use the uniform. I think that makes a lot of sense for testing the box, since we are supposed to 'protect uniformly' against all possible realizations of the uncertainty. But I don't think it has the same abstract meaning for simulating an elliptical uncertainty set, since the 2-norm drives the uncertainty away from the edges of the defined perturbation for most of the variables.

**Comment by 1ozturkbe** [comment]
I do agree that this should be an option.

**Comment by 1ozturkbe** [comment]
This has been done in the PR #18.  The older codes that don't have a fourth argument for generate_model_properties still simulate from the uniform, but with the fourth argument of 'normal' can simulate from a Gaussian.

**Comment by 1ozturkbe** [comment]
I have actually altered this to now simulate from a truncated Gaussian, since this will allow us to have guarantees that we protect for 3 standard deviations of the uncertain parameters for Gamma = 1.

**Comment by 1ozturkbe** [comment]
Now we have the option to sample from either distribution. Closing for now.
