### ISSUE TITLE
subinplace deprecation

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#20]
Yo, @bqpd and @alisaab, the deprecation of subinplace breaks SPs in robust... need to debug now.

**Comment by 1ozturkbe** [comment]
What is the preferred method to do subinplace for constraints, but I only want to substitute it constants? @bqpd 
The current setup is
```python
            cs.subinplace(solution["constants"])
```
I tried:
``` python
            css = cs.sub(solution['constants'])
```
But this doesn't work because
```python
AttributeError: 'SignomialInequality' object has no attribute 'sub'
```
Seems problematic.

**Comment by 1ozturkbe** [comment]
Also, [the documentation still says that subinplace works](https://gpkit.readthedocs.io/en/latest/advancedcommands.html?highlight=subinplace).

**Comment by whoburg** [comment]
this should be an issue in the GPkit repo, no? (especially the documentation piece)

**Comment by 1ozturkbe** [comment]
Aight, in #18 I have implemented a fix. But still frustrating that we can't sub into a signomial inequality, but rather have to sub into the separate nomials. And yes, I thought this issue was going to be robust specific but it turns out to be more crucial. Will ref over at the gpkit issues.
