### ISSUE TITLE
print_simulation_data setup time comparison

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#22]
Hey @alisaab, I noticed something in print_simulation_data that seemed odd
```python
    file_id.write('\t\t\t' + 'Relative setup time: %s\n' %
                      (robust_model_solution['setuptime'] / float(nominal_model_solve_time)))
```
The setup time of the robust model is compared to the nominal solve time. Shouldn't it be compared to the nominal setup time, or is this as intended?

**Comment by alisaab** [comment]
There is no nominal setup time. We might say that the time taken to define a model is the nominal setup time, but I think this is a very small number, what do you think?

**Comment by 1ozturkbe** [comment]
I think that should be the comparison, not the solve time. I think it misrepresents the overhead.

**Comment by 1ozturkbe** [comment]
@bqpd solutions store ['soltime'], but do they store setup time somewhere?

**Comment by 1ozturkbe** [comment]
I'm just going to close this, since it seems like the setup time of a nominal GP model is negligible compared to the solve time.
