### ISSUE TITLE
Consistent issues in simulations for variable gamma. 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#23]
I am getting some unexpected, somewhat annoying behavior with the simulations. My probability of failure graph will monotonically decrease, but have an odd spike to 1 at some point in the iteration, which will depend on my realization of the uncertain parameters (same for all simulations). I am trying to debug as we speak.

**Comment by 1ozturkbe** [comment]
As a note, I'm on the cleanUps2 branch, and running SimPleAC_probOfFailure in robustSPpaper. About to post diagrams soon.

**Comment by 1ozturkbe** [comment]
![figure_2](https://user-images.githubusercontent.com/15684191/49666948-83ff1100-fa27-11e8-809c-837a5a20fa0e.png)

**Comment by 1ozturkbe** [comment]
I have checked the sensitivities around the anomalous solution. Doesn't look anything out of the ordinary.

**Comment by 1ozturkbe** [comment]
@alisaab have you seen this behavior before? I get it very consistently.

**Comment by 1ozturkbe** [comment]
oy, thanks for the expert advice! I have been struggling with this for days!

**Comment by bqpd** [comment]
(sorry, I should make that tolerance a class attribute of
SingleEquationConstraint so you can set it higher for your purposes!)

**Comment by 1ozturkbe** [comment]
That would be great! In the meanwhile, I'm not sure how to change the infeasibility tolerance. Lmk what classes I need to muck with.

**Comment by alisaab** [comment]
@1ozturkbe Check line 456 of nomials/math.py. The threshold is 1e-6 right now, you can change it to 1e-3, I think it will work.

**Comment by 1ozturkbe** [comment]
@alisaab @bqpd I have confirmed over multiple trials that it does indeed work when the tolerance is lowered.

**Comment by alisaab** [comment]
great! I think the tolerance should be an optional attribute in GPkit @bqpd

**Comment by bqpd** [comment]
it will be soon when Berk's PR https://github.com/convexengineering/gpkit/pull/1382 is merged!

**Comment by 1ozturkbe** [comment]
This is now resolved, since the global tolerance is now 1e-3!
