### ISSUE TITLE
Commit 129f778d1d is breaking everything. 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#24]
Hey @alisaab, I just realized that there are some serious bugs in robust after you pushed this commit in cleanUps2. I noticed that there are erroneous solutions only after I started sketching the aircraft! 

I traced the issue back to that commit by trying to use previous commits in cleanUps2 and see whether the solutions matched master. And they didn't, until before the commit titled 'removing pr and replacing by r'. 

You can see a demo of this [by running SimPleAC_fuseShrink at this commit.](https://github.com/1ozturkbe/robustSPpaper/commit/dede5c5d187dd0de40a1478eee4c5ec5b7dfeba3). Look at the printout to see the wing areas at the end. This is followed by a drawing (to scale) of the resulting aircraft. Seems like the formulation got messed up once pr got changed to r. Would appreciate the help here!

**Comment by 1ozturkbe** [comment]
I have pushed a working version of the commit '129f778d1d' in branch bugFix.

**Comment by 1ozturkbe** [comment]
And again, confirming it is a buggy commit. I just reverted that in cleanUps2, and now the output matches master. So here are the links to the different versions of robust to run: 
[Master with subinplace fix](https://github.com/convexengineering/robust/commit/fe5698fd90579a150ddef34999d2280d990771d0)
[Bugfix with buggy pr to r commit](https://github.com/convexengineering/robust/commit/59916571c525137b3249302053485533ad90d397)
[cleanUps2 with reverted buggy commit, which works.](https://github.com/convexengineering/robust/pull/18/commits/1acdd3931709f9a9dcec1ea4174a00cd424c7638)
Phew that's a lot, but hope it helps.

**Comment by 1ozturkbe** [comment]
I also noticed that the revert requires switching back to the pr version of SimPleAC at [commit  9e26254e68f7c1469 of gplibrary](https://github.com/convexengineering/gplibrary/commit/9e26254e68f7c1469e7d8d809ccf3d3c29794363).

**Comment by 1ozturkbe** [comment]
I went through the code and couldn't figure out what the issue was. Seems like the conversion from pr (percentage change in real space) to r (e^pr) makes sense. Hmmm.

**Comment by 1ozturkbe** [comment]
Figured out the issue. When you changed robustify monomial from this:
```python
        return monomial * np.exp(self.setting.get('gamma') * l_norm) / np.exp(total_center)
```
to
```python
        return monomial * self.setting.get('gamma') * np.exp(l_norm)
```
There is a dropped exponential. The only way to allow gamma to not be in the exponential is to take a Taylor expansion. 
```python
       return monomial * (1.+g+1./2.*g**2+1./6.*g**3+1./24.*g**4)**(l_norm)
```
but you can't do this either, since you cannot take non-integer powers of posynomials. I am reformulating as I speak.

**Comment by 1ozturkbe** [comment]
Alright, I have resolved this issue in cleanUps2. The reformulation has required auxiliary variables added to every monomial constraint. so that there are no powers taken of the Taylor expansion of the posynomial.

**Comment by alisaab** [comment]
hey @1ozturkbe , sorry for the late reply. I was trying to remember why we did those changes, I think here: return monomial * self.setting.get('gamma') * np.exp(l_norm), gamma is actually not between 0 and 1, but between 1 and e^1. I did this to make the goal programming work since gamma here can be a variable. The taking the Taylor exapansion is a smart move, gamma can be between 0 and 1 now

**Comment by 1ozturkbe** [comment]
This has been resolved in master. Working as intended now with the Taylor approximation.
