### ISSUE TITLE
Remove gassolar from requirements

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#25]
It is really silly that gassolar is part of the testing, especially since it is no longer an active repo. We should be pulling models straight from gplibrary instead. I can fix this in the near future.

**Comment by 1ozturkbe** [comment]
This is especially annoying because gassolar has gpfit as one of its requirements. Gaaaah, this is a travesty and should not be allowed to persist.

**Comment by 1ozturkbe** [comment]
Also, gassolar doesn't even solve in the nominal case. This is a priority.

**Comment by bqpd** [comment]
that's because it's been updated for a pending gpkit pull request

**Comment by 1ozturkbe** [comment]
is that parse_variables?

**Comment by bqpd** [comment]
naw, it's a change to how variables are named if they're a part of named models...from e.g. "c_Aircraft/Wing" to "Aircraft.Wing.c"

**Comment by bqpd** [comment]
I would definitely recommend keeping gassolar in the requirements! Complex real-world examples are great for finding unexpected bugs.

**Comment by 1ozturkbe** [comment]
Yes, but I currently have working models that I can solve and make tests with. Currently, gassolar doesn't work, and there are no tests written with it. It's a pain. I will keep the gassolar code in the repo, but will remove it for the sake of making the install less dependent on non-critical code. Also, documentation (or a first stab at it) will be up soon.

**Comment by bqpd** [comment]
gassolar master now runs on gpkit master :)

**Comment by whoburg** [comment]
YES!!! Thanks @bqpd for being a stickler for keeping tests of integrated examples around.
