### ISSUE TITLE
Reason why robust doesn't have gpkit.model's methods? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#3]
Eg. the fact that you can't call model.variables_byname is a pain. Or am I totally inept in python?

**Comment by bqpd** [comment]
Hmm, looking at the example are you making a RobustModel object?
Unfortunately those aren't currently inheriting from Model... You can find
the equivalent model at .robust_model

(This will change soon)

**Comment by 1ozturkbe** [comment]
Yeah, I take an original model, and robustify it. Looking forward to having good inheritance in robust!

**Comment by alisaab** [comment]
actually it is important for me to hear your complaints so that things can become better. I will try with Ned to have inheritance
