### ISSUE TITLE
What does a variable being 'indirectly_uncertain' mean? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#39]
@alisaab I would like to loop you back in a little bit since I am modernizing this repo and adding more functionality. I'm confused about how a variable can be indirectly uncertain? Let me know what that means!

**Comment by alisaab** [comment]
Lets assume that 'a' and 'b' are uncertain variables, and that c = a**2b, then we say b is indirectly uncertain.

the way I used to define it is I define c as a variable, and c.key.rel will be a**2b, I would then replace the variable c  by a**2b when I am robustiying the linear constraints. Check the functions replace_indirect_uncertain_variable_by_equivalent in robust_gp_tools. This might not be the most user friendly way to define an indirectly uncertain variable, but it was working for me.

**Comment by 1ozturkbe** [comment]
Hmm I understand. Thanks for the heads up.
