### ISSUE TITLE
Cannot do nominalsolve with SPs, and weird arguments for nominalsolve? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#4]
In this case, m is a robust instance of SimPleAC. And also, why is a Model a required input for nominalsolve?
 Why doesn't it just solve ```self```? Here is the error:
```python
In [27]: sol = m.nominalsolve(m)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-c5721bfa8ca4> in <module>()
----> 1 sol = m.nominalsolve(m)

C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\code\robust\Robust.py in nominalsolve(model, verbosity)
    426             return model.solve(verbosity=verbosity)
    427         except:
--> 428             return model.localsolve(verbosity=verbosity)
    429
    430     def get_robust_model(self):

AttributeError: RobustModel instance has no attribute 'localsolve'
```
It seems to understand the model is SP, but thinks localsolve is an attribute. I guess there is no method localsolve?

**Comment by alisaab** [comment]
weirdly,  the nominal solve does not take a robust model and return the nominal solution, this function is static and is meant to be private for the class and not to be used by the users. to get the nominal solution try m.nominal_solve. This will be fixed to become more intuitive.

**Comment by alisaab** [comment]
m.nominalsolve() will solve the nominal problem now.

**Comment by 1ozturkbe** [comment]
Thanks @alisaab !
