### ISSUE TITLE
Testing master of robust as well, with build status. 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#46]
@bqpd currently robust does not build and test the master branch (like in gpkit_Push). I would like to have robust have build indicators as well. How do I get this to happen? Also, it would be nice if I actually learn this for the long run, since there will be other repos I have to test. Are there any resources for this?

**Comment by bqpd** [comment]
I'll come by and show you in person sometime this week! It's just jenkins + bash scripting; I'm working to clean up some of the existing jobs, so this'll be a good chance to give an overview.

**Comment by 1ozturkbe** [comment]
This will be integrated in PR #47 .
