### ISSUE TITLE
Issues with simulation results (0 PoF)? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#48]
Hello @bqpd , please feel free to put the problematic code here, so I can test it. I cannot replicate the issues on my machine, at least not with simple_ac from robust.testing.models.

**Comment by 1ozturkbe** [comment]
Hmmm, still can't replicate. I will get back to you, I am digging in.

**Comment by bqpd** [comment]
are you on the master branch of solar, unmodified?

**Comment by 1ozturkbe** [comment]
Tbh I was trying signomial simple flight first, since I know that code better. But yes, I am on master of solar.

**Comment by 1ozturkbe** [comment]
The crazy thing is that my non-print-based method gives the right results, whereas the printing does not...

**Comment by 1ozturkbe** [comment]
Also, now I can no longer replicate it... My results match the old results... gah! But I noticed some issues with the Best Pairs method with elliptical uncertainty... for some reason I am getting that the model is infeasible. This is going to be hard to debug.

**Comment by 1ozturkbe** [comment]
I believe we have figured this out @bqpd, so closing this for now.
