### ISSUE TITLE
Better diff for RobustModel solutions needed.

### ISSUE THREAD

**Issue by bqpd** [convexengineering/robust#58]
see https://acdl.mit.edu/csi/job/CE_gpkit_PR_research_models/445/

Works on my computer with both that coverage PR branch and gpkit master, so just flagging in case it reproduces easily on your computer, will add more information as it comes.

**Comment by bqpd** [comment]
failure seen again at https://acdl.mit.edu/csi/job/CE_gpkit_PR_research_models/448/buildnode=windows10x64,optimizer=mosek/

**Comment by bqpd** [comment]
and at https://acdl.mit.edu/csi/job/CE_gpkit_PR_research_models/449/ (on windows and reynolds)

**Comment by bqpd** [comment]
per https://github.com/convexengineering/gpkit/pull/1506, the failures are caused by https://github.com/convexengineering/gpkit/pull/1505, but I still can't reproduce them here :(

**Comment by bqpd** [comment]
reproduced on py3.7, will fix

**Comment by bqpd** [comment]
@1ozturkbe just to make sure you saw this...recent test_table_diff errors seem to be caused by a gpkit commit, I finally got it to reproduce

**Comment by bqpd** [comment]
uh. I confirmed it reproduced and came back, and now cannot reproduce it (this is before I pulled your changes)

???

looking at the test...there both seem to be significant differences and, how does assertAlmostEqual work on lists of strings?

**Comment by bqpd** [comment]
I seem to be getting the old values (`L/D & 1.98e+01 & 1.94e+01 & 2.02e+01 & 2.04e+01` etc.) reliably now...which causes me to fail on the most recent commit to robust

**Comment by 1ozturkbe** [comment]
Firstly, the values you posted are the ones on master, so there should be no problems there.

**Comment by 1ozturkbe** [comment]
Secondly, I am 95% certain that the improvements in solutions are due to improvements in scipy.optimize due to their 1.5 release.

**Comment by 1ozturkbe** [comment]
You are right that assertAlmostEqual behavior is confusing with strings, and I'm still not certain why it works. I do have it on my bucket list to figure out better ways to diff robust models, since the constraints are fundamentally different depending on the linearization method and the uncertainty set type.

**Comment by 1ozturkbe** [comment]
I have changed this to an assertTrue to make sure that tests pass. I am changing this issue to be about better diffing for RobustModels.

**Comment by bqpd** [comment]
ohhh interesting.

**Comment by bqpd** [comment]
seems to be working on Jenkins at https://github.com/convexengineering/gpkit/pull/1507!
