### ISSUE TITLE
Adding SameModel and EqualModel to gpkit? 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#6]
Hey @alisaab, I think it would be useful to add these to gpkit since there is no other way to copy the models. It would save everyone some headache.

**Comment by alisaab** [comment]
Hey @1ozturkbe , yes I think this is a good idea. SameModel flattens the constraints and doesn't account for the model hierarchy, but EqualModel is meant to copy the model with all its substitutions while preserving hierarchy

**Comment by 1ozturkbe** [comment]
It would be great if you could create a new branch and PR in gpkit, probably under gpkit.Model, and I can take care of the rest.

**Comment by 1ozturkbe** [comment]
@alisaab could you explain what the issue was with SameModel and EqualModel, and why they didn't make good 'copies' of the models? This seems like an easy issue to close, and I would like to figure out why it is so hard to make duplicates.
