### ISSUE TITLE
robust should pull its models from gplibrary

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/robust#8]
@alisaab I can help with this. It irritates me that we have no good copy of simple_wing in gplibrary as well. Let me see if I can get this to work.

**Comment by alisaab** [comment]
@1ozturkbe the SimPleAC_mission is not working for now (not converging), but the simple_wing (that was there originally is working)

**Comment by 1ozturkbe** [comment]
ok, I'm back in town and can look at this again.

**Comment by 1ozturkbe** [comment]
@alisaab can we make it a priority to fix this? I have been making pushes to robustSPpaper but I am seeing some odd behavior with the feasibility check using designed_model, especially for the box uncertainty set. I'll tag you on interesting commits.

**Comment by 1ozturkbe** [comment]
This is related to issue #25, so I'm going to close this for the sake of having fewer TODOs.
